
FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de configuration d'abord (pour optimiser le cache)
COPY package*.json ./

# Installer Angular CLI globalement
RUN npm install



# Copier le reste du code
COPY . .



RUN npm run build --configuration=dev
# Run stage
FROM nginx:alpine
COPY --from=build /app/dist/admin-front /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
