
FROM node:20-alpine AS build

WORKDIR /app

# Copier les fichiers de configuration d'abord (pour optimiser le cache)
COPY package*.json ./

# Installer Angular CLI globalement
RUN npm install



# Copier le reste du code
COPY . .



RUN npm run build --configuration=production
# Run stage
FROM nginx:alpine
COPY --from=build /app/dist/admin-front/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 81
 CMD ["nginx", "-g", "daemon off;"]
