# Utiliser Node.js 22.5.1
FROM node:18-alpine

WORKDIR /app

# copy everything to app
COPY . .

# Installer Angular CLI globalement
RUN npm install && npm run build --prod

# Stage 2: Serve via Nginx
FROM nginx:alpine

COPY --from=build /app/dist/your-angular-app /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
